- name: Install apps
  hosts: app
  become: true
  tasks:
    - name: Install apps
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: 
        - ruby-full
        - ruby-bundler
        - build-essential
        - git 
